env STEAM_COMPAT_DATA_PATH=/mnt/VG_00/PUBLIC-LIBRARY/PRE-INSTALLED-GAMES/WINEPREFIX/306760  "/mnt/VG_00/PUBLIC-LIBRARY/PRE-INSTALLED-GAMES/steamapps/steamapps/common/Proton 6.3/proton" run "game.exe"
